version: '3.8'  # Укажите версию Compose  
  
services:  
  link-shortener:  
    build:  
      context: .
      dockerfile: Dockerfile  
    ports:  
      - "44044:44044"
    environment:  
      - SOME_ENV_VAR=value
    depends_on:
      - postgres
    networks:  
      - backend  
    entrypoint: ["./link_shortener_lin", "--in_memory=${IN_MEMORY}"] 
   
  postgres:  
    container_name: postgres_link_shortener  
    image: postgres:16.4  
    environment:  
      POSTGRES_USER: postgres  
      POSTGRES_PASSWORD: admin  
      POSTGRES_DB: link_shortener  
    volumes:  
      - ../postgres-data:/var/lib/postgresql/data  
    ports:  
      - "5432:5432"  
    networks:  
      - backend  
  
networks:  
  backend:  
